---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ntwitm.
--- DateTime: 2026/2/14 21:36
---
-- 原子覆盖 Token/Version（不先 DEL，避免主从切换时丢失 key）
local tokenKey = KEYS[1]
local refreshKey = KEYS[2]
local versionKey = KEYS[3]
local newVersionKey = KEYS[4]
local newToken = ARGV[1]
local refreshToken = ARGV[2]
local version = tonumber(ARGV[3])
local tokenExpireSeconds = tonumber(ARGV[4])
local refreshExpireSeconds = tonumber(ARGV[5])
local versionExpireSeconds = tonumber(ARGV[6])
local newVersionExpireSeconds = tonumber(ARGV[7])
-- 直接 SET 覆盖旧值（不先 DEL，避免主从切换时 DEL 已同步但 SET 未落盘导致 key 丢失）
redis.call('SET', tokenKey, newToken, 'EX', tokenExpireSeconds)
redis.call('SET', refreshKey, refreshToken, 'EX', refreshExpireSeconds)
redis.call('SET', versionKey, version, 'EX', versionExpireSeconds)
redis.call('expire',newVersionKey,newVersionExpireSeconds)
local result ={
    code = 1,
    message ='update token,refreshToken,version success'
}
return cjson.encode(result)