---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ntwitm.
--- DateTime: 2025/7/22 18:58
---
local id = redis.call("get",KEYS[1])
if (id == ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0