---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ntwitm.
--- DateTime: 2026/2/13 23:16
---
-- KEYS[1]: refreshKey = "refresh:user:" .. userId
-- KEYS[2]: tokenKey = "login:token:" .. userId
-- KEYS[3]: versionKey = "token:version:" .. userId

-- ARGV[1]: oldRefreshToken (请求携带的旧 RefreshToken)
-- ARGV[2]: newRefreshToken (新生成的 RefreshToken)
-- ARGV[3]: refreshTokenExpireSeconds (新 RefreshToken 的过期秒数，例如 7天 = 604800)
-- ARGV[4]: newToken (新生成的 access token)
-- ARGV[5]: tokenExpireSeconds (新 token 的过期秒数，例如 30分钟 = 1800)
-- ARGV[6]: version (从过期 JWT 中解析出的旧版本号)
-- ARGV[7]: versionExpireSeconds (版本号的过期秒数，与 refreshToken 保持一致)
-- ARGV[8]: newVersion (新生成的版本号，例如当前时间戳)

local RefreshTokenKey = KEYS[1]
local tokenKey = KEYS[2]
local validVersionKey = KEYS[3]
local newVersionKey = KEYS[4]

local oldRefreshToken = ARGV[1]
local newRefreshToken = ARGV[2]
local refreshTokenExpireSeconds = tonumber(ARGV[3])
local newToken = ARGV[4]
local tokenExpireSeconds = tonumber(ARGV[5])
local version = tonumber(ARGV[6])
local versionExpireSeconds = tonumber(ARGV[7])
local newVersion = tonumber(ARGV[8])
local newVersionExpireSeconds = tonumber(ARGV[9])

-- 1. 检查原始版本号是否存在
local orginVersion = redis.call('get', validVersionKey)
if not orginVersion then
    return 431  -- ORIGIN_VERSION_NULL
end

-- 2. 比登录时间还早的token不可使用
if tonumber(orginVersion) > version then
    return 413  -- TOKEN_BEFORE_LOGIN
end

-- 3. 检查RefreshToken是否存在
local exists = redis.call('EXISTS', RefreshTokenKey)
if exists == 0 then
    return 421  -- REFRESH_TOKEN_NOT_FOUND
end

-- 4. 验证RefreshToken是否匹配
local storedToken = redis.call('GET', RefreshTokenKey)
if storedToken ~= oldRefreshToken then
    return 422  -- REFRESH_TOKEN_MISMATCH
end

-- 5. 更新所有token和版本信息
redis.call('SET', RefreshTokenKey, newRefreshToken, 'EX', refreshTokenExpireSeconds)
redis.call('SET', tokenKey, newToken, 'EX', tokenExpireSeconds)
redis.call('SET', validVersionKey, newVersion, 'EX', versionExpireSeconds)
redis.call('EXPIRE', newVersionKey, newVersionExpireSeconds)

-- 6. 返回成功
return 200  -- SUCCESS