---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ntwitm.
--- DateTime: 2025/7/25 17:42
---
local voucherId = ARGV[1]
local userId = ARGV[2]
local stockKey ='seckill:stock:'..voucherId
local orderKey = 'seckill:order:'..voucherId
if (tonumber(redis.call('get',stockKey)) <= 0) then
    return 1
end
if (redis.call("sismember",orderKey,userId) == 1) then
    return 2
end
redis.call("incrby",stockKey,-1)
redis.call("sadd",orderKey,userId)
return 0
--local  count = redis.call("get","seckill:stock:"..voucherId)
--if count > 0 then
--    local orderCount = redis.call()
--    if orderCount>0 then
--        return 2
--    else
--        count = count-1
--        redis.call("set","seckill:stock:"..voucherId,count)
--        local set = redis.call("sget","")
--        redis.call("",)
--        return 0
--    end
--end
--return 1